sudo: required

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
cache: pip

before_install:
  - sudo apt-get install -y python python-dev swig python-pip build-essential git libpulse-dev
  
install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python -m unittest discover tests
  - coverage run -m unittest discover

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'