sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install -y python python-dev swig python-pip build-essential git libpulse-dev
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests